### ISSUE TITLE
Discovery issues with v6 and Keycloak

### ISSUE THREAD

**Issue by jezikk** [panva/openid-client#737]
### What happened?

I'm using Keycloak as IDP with different front and back channels in Docker env.
- Front channel: `http://localhost:8080/realms/hektor`
- Back channel: `http://identity-provider-web:8080/realms/hektor`

Getting the following error:
```
ClientError: discovered metadata issuer does not match the expected issuer
```

In v5 it works ok:

```ts
    const host = this.getHostUrl(request);
    const issuer = await Issuer.discover(process.env.IDP_URL); // http://identity-provider-web:8080/realms/hektor

    const client = new issuer.Client({
      client_id: process.env.IDP_CLIENT_ID,
      client_secret: process.env.IDP_CLIENT_SECRET,
      redirect_uris: [`${host}/auth/callback`],
      response_types: ["code"],
    });
```

```
2024-12-01 09:32:15  {
2024-12-01 09:32:15   claim_types_supported: [ 'normal' ],
2024-12-01 09:32:15   claims_parameter_supported: true,
2024-12-01 09:32:15   grant_types_supported: [
2024-12-01 09:32:15     'authorization_code',
2024-12-01 09:32:15     'implicit',
2024-12-01 09:32:15     'refresh_token',
2024-12-01 09:32:15     'password',
2024-12-01 09:32:15     'client_credentials',
2024-12-01 09:32:15     'urn:openid:params:grant-type:ciba',
2024-12-01 09:32:15     'urn:ietf:params:oauth:grant-type:device_code'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   request_parameter_supported: true,
2024-12-01 09:32:15   request_uri_parameter_supported: true,
2024-12-01 09:32:15   require_request_uri_registration: true,
2024-12-01 09:32:15   response_modes_supported: [
2024-12-01 09:32:15     'query',
2024-12-01 09:32:15     'fragment',
2024-12-01 09:32:15     'form_post',
2024-12-01 09:32:15     'query.jwt',
2024-12-01 09:32:15     'fragment.jwt',
2024-12-01 09:32:15     'form_post.jwt',
2024-12-01 09:32:15     'jwt'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   token_endpoint_auth_methods_supported: [
2024-12-01 09:32:15     'private_key_jwt',
2024-12-01 09:32:15     'client_secret_basic',
2024-12-01 09:32:15     'client_secret_post',
2024-12-01 09:32:15     'tls_client_auth',
2024-12-01 09:32:15     'client_secret_jwt'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   issuer: 'http://localhost:8080/realms/hektor',
2024-12-01 09:32:15   authorization_endpoint: 'http://localhost:8080/realms/hektor/protocol/openid-connect/auth',
2024-12-01 09:32:15   token_endpoint: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/token',
2024-12-01 09:32:15   introspection_endpoint: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/token/introspect',
2024-12-01 09:32:15   userinfo_endpoint: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/userinfo',
2024-12-01 09:32:15   end_session_endpoint: 'http://localhost:8080/realms/hektor/protocol/openid-connect/logout',
2024-12-01 09:32:15   frontchannel_logout_session_supported: true,
2024-12-01 09:32:15   frontchannel_logout_supported: true,
2024-12-01 09:32:15   jwks_uri: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/certs',
2024-12-01 09:32:15   check_session_iframe: 'http://localhost:8080/realms/hektor/protocol/openid-connect/login-status-iframe.html',
2024-12-01 09:32:15   acr_values_supported: [ '0', '1' ],
2024-12-01 09:32:15   response_types_supported: [
2024-12-01 09:32:15     'code',
2024-12-01 09:32:15     'none',
2024-12-01 09:32:15     'id_token',
2024-12-01 09:32:15     'token',
2024-12-01 09:32:15     'id_token token',
2024-12-01 09:32:15     'code id_token',
2024-12-01 09:32:15     'code token',
2024-12-01 09:32:15     'code id_token token'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   subject_types_supported: [ 'public', 'pairwise' ],
2024-12-01 09:32:15   id_token_signing_alg_values_supported: [
2024-12-01 09:32:15     'PS384', 'RS384',
2024-12-01 09:32:15     'EdDSA', 'ES384',
2024-12-01 09:32:15     'HS256', 'HS512',
2024-12-01 09:32:15     'ES256', 'RS256',
2024-12-01 09:32:15     'HS384', 'ES512',
2024-12-01 09:32:15     'PS256', 'PS512',
2024-12-01 09:32:15     'RS512'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   id_token_encryption_alg_values_supported: [ 'RSA-OAEP', 'RSA-OAEP-256', 'RSA1_5' ],
2024-12-01 09:32:15   id_token_encryption_enc_values_supported: [
2024-12-01 09:32:15     'A256GCM',
2024-12-01 09:32:15     'A192GCM',
2024-12-01 09:32:15     'A128GCM',
2024-12-01 09:32:15     'A128CBC-HS256',
2024-12-01 09:32:15     'A192CBC-HS384',
2024-12-01 09:32:15     'A256CBC-HS512'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   userinfo_signing_alg_values_supported: [
2024-12-01 09:32:15     'PS384', 'RS384',
2024-12-01 09:32:15     'EdDSA', 'ES384',
2024-12-01 09:32:15     'HS256', 'HS512',
2024-12-01 09:32:15     'ES256', 'RS256',
2024-12-01 09:32:15     'HS384', 'ES512',
2024-12-01 09:32:15     'PS256', 'PS512',
2024-12-01 09:32:15     'RS512', 'none'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   userinfo_encryption_alg_values_supported: [ 'RSA-OAEP', 'RSA-OAEP-256', 'RSA1_5' ],
2024-12-01 09:32:15   userinfo_encryption_enc_values_supported: [
2024-12-01 09:32:15     'A256GCM',
2024-12-01 09:32:15     'A192GCM',
2024-12-01 09:32:15     'A128GCM',
2024-12-01 09:32:15     'A128CBC-HS256',
2024-12-01 09:32:15     'A192CBC-HS384',
2024-12-01 09:32:15     'A256CBC-HS512'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   request_object_signing_alg_values_supported: [
2024-12-01 09:32:15     'PS384', 'RS384',
2024-12-01 09:32:15     'EdDSA', 'ES384',
2024-12-01 09:32:15     'HS256', 'HS512',
2024-12-01 09:32:15     'ES256', 'RS256',
2024-12-01 09:32:15     'HS384', 'ES512',
2024-12-01 09:32:15     'PS256', 'PS512',
2024-12-01 09:32:15     'RS512', 'none'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   request_object_encryption_alg_values_supported: [ 'RSA-OAEP', 'RSA-OAEP-256', 'RSA1_5' ],
2024-12-01 09:32:15   request_object_encryption_enc_values_supported: [
2024-12-01 09:32:15     'A256GCM',
2024-12-01 09:32:15     'A192GCM',
2024-12-01 09:32:15     'A128GCM',
2024-12-01 09:32:15     'A128CBC-HS256',
2024-12-01 09:32:15     'A192CBC-HS384',
2024-12-01 09:32:15     'A256CBC-HS512'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   registration_endpoint: 'http://identity-provider-web:8080/realms/hektor/clients-registrations/openid-connect',
2024-12-01 09:32:15   token_endpoint_auth_signing_alg_values_supported: [
2024-12-01 09:32:15     'PS384', 'RS384',
2024-12-01 09:32:15     'EdDSA', 'ES384',
2024-12-01 09:32:15     'HS256', 'HS512',
2024-12-01 09:32:15     'ES256', 'RS256',
2024-12-01 09:32:15     'HS384', 'ES512',
2024-12-01 09:32:15     'PS256', 'PS512',
2024-12-01 09:32:15     'RS512'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   introspection_endpoint_auth_methods_supported: [
2024-12-01 09:32:15     'private_key_jwt',
2024-12-01 09:32:15     'client_secret_basic',
2024-12-01 09:32:15     'client_secret_post',
2024-12-01 09:32:15     'tls_client_auth',
2024-12-01 09:32:15     'client_secret_jwt'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   introspection_endpoint_auth_signing_alg_values_supported: [
2024-12-01 09:32:15     'PS384', 'RS384',
2024-12-01 09:32:15     'EdDSA', 'ES384',
2024-12-01 09:32:15     'HS256', 'HS512',
2024-12-01 09:32:15     'ES256', 'RS256',
2024-12-01 09:32:15     'HS384', 'ES512',
2024-12-01 09:32:15     'PS256', 'PS512',
2024-12-01 09:32:15     'RS512'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   authorization_signing_alg_values_supported: [
2024-12-01 09:32:15     'PS384', 'RS384',
2024-12-01 09:32:15     'EdDSA', 'ES384',
2024-12-01 09:32:15     'HS256', 'HS512',
2024-12-01 09:32:15     'ES256', 'RS256',
2024-12-01 09:32:15     'HS384', 'ES512',
2024-12-01 09:32:15     'PS256', 'PS512',
2024-12-01 09:32:15     'RS512'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   authorization_encryption_alg_values_supported: [ 'RSA-OAEP', 'RSA-OAEP-256', 'RSA1_5' ],
2024-12-01 09:32:15   authorization_encryption_enc_values_supported: [
2024-12-01 09:32:15     'A256GCM',
2024-12-01 09:32:15     'A192GCM',
2024-12-01 09:32:15     'A128GCM',
2024-12-01 09:32:15     'A128CBC-HS256',
2024-12-01 09:32:15     'A192CBC-HS384',
2024-12-01 09:32:15     'A256CBC-HS512'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   claims_supported: [
2024-12-01 09:32:15     'aud',
2024-12-01 09:32:15     'sub',
2024-12-01 09:32:15     'iss',
2024-12-01 09:32:15     'auth_time',
2024-12-01 09:32:15     'name',
2024-12-01 09:32:15     'given_name',
2024-12-01 09:32:15     'family_name',
2024-12-01 09:32:15     'preferred_username',
2024-12-01 09:32:15     'email',
2024-12-01 09:32:15     'acr'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   scopes_supported: [
2024-12-01 09:32:15     'openid',
2024-12-01 09:32:15     'microprofile-jwt',
2024-12-01 09:32:15     'email',
2024-12-01 09:32:15     'acr',
2024-12-01 09:32:15     'audience-product-core',
2024-12-01 09:32:15     'address',
2024-12-01 09:32:15     'phone',
2024-12-01 09:32:15     'roles',
2024-12-01 09:32:15     'profile',
2024-12-01 09:32:15     'audience-eshop-core',
2024-12-01 09:32:15     'basic',
2024-12-01 09:32:15     'web-origins',
2024-12-01 09:32:15     'offline_access'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   code_challenge_methods_supported: [ 'plain', 'S256' ],
2024-12-01 09:32:15   tls_client_certificate_bound_access_tokens: true,
2024-12-01 09:32:15   revocation_endpoint: 'http://localhost:8080/realms/hektor/protocol/openid-connect/revoke',
2024-12-01 09:32:15   revocation_endpoint_auth_methods_supported: [
2024-12-01 09:32:15     'private_key_jwt',
2024-12-01 09:32:15     'client_secret_basic',
2024-12-01 09:32:15     'client_secret_post',
2024-12-01 09:32:15     'tls_client_auth',
2024-12-01 09:32:15     'client_secret_jwt'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   revocation_endpoint_auth_signing_alg_values_supported: [
2024-12-01 09:32:15     'PS384', 'RS384',
2024-12-01 09:32:15     'EdDSA', 'ES384',
2024-12-01 09:32:15     'HS256', 'HS512',
2024-12-01 09:32:15     'ES256', 'RS256',
2024-12-01 09:32:15     'HS384', 'ES512',
2024-12-01 09:32:15     'PS256', 'PS512',
2024-12-01 09:32:15     'RS512'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   backchannel_logout_supported: true,
2024-12-01 09:32:15   backchannel_logout_session_supported: true,
2024-12-01 09:32:15   device_authorization_endpoint: 'http://localhost:8080/realms/hektor/protocol/openid-connect/auth/device',
2024-12-01 09:32:15   backchannel_token_delivery_modes_supported: [ 'poll', 'ping' ],
2024-12-01 09:32:15   backchannel_authentication_endpoint: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/ext/ciba/auth',
2024-12-01 09:32:15   backchannel_authentication_request_signing_alg_values_supported: [
2024-12-01 09:32:15     'PS384', 'RS384',
2024-12-01 09:32:15     'EdDSA', 'ES384',
2024-12-01 09:32:15     'ES256', 'RS256',
2024-12-01 09:32:15     'ES512', 'PS256',
2024-12-01 09:32:15     'PS512', 'RS512'
2024-12-01 09:32:15   ],
2024-12-01 09:32:15   require_pushed_authorization_requests: false,
2024-12-01 09:32:15   pushed_authorization_request_endpoint: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/ext/par/request',
2024-12-01 09:32:15   mtls_endpoint_aliases: {
2024-12-01 09:32:15     token_endpoint: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/token',
2024-12-01 09:32:15     revocation_endpoint: 'http://localhost:8080/realms/hektor/protocol/openid-connect/revoke',
2024-12-01 09:32:15     introspection_endpoint: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/token/introspect',
2024-12-01 09:32:15     device_authorization_endpoint: 'http://localhost:8080/realms/hektor/protocol/openid-connect/auth/device',
2024-12-01 09:32:15     registration_endpoint: 'http://identity-provider-web:8080/realms/hektor/clients-registrations/openid-connect',
2024-12-01 09:32:15     userinfo_endpoint: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/userinfo',
2024-12-01 09:32:15     pushed_authorization_request_endpoint: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/ext/par/request',
2024-12-01 09:32:15     backchannel_authentication_endpoint: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/ext/ciba/auth'
2024-12-01 09:32:15   },
2024-12-01 09:32:15   authorization_response_iss_parameter_supported: true
2024-12-01 09:32:15 }
```

In v6 i'm getting the following error:
```ts
    const host = this.getHostUrl(request);
    const idpUrl = new URL(process.env.IDP_URL); // http://identity-provider-web:8080/realms/hektor

      const config = await client.discovery(
          idpUrl,
          process.env.IDP_CLIENT_ID,
          process.env.IDP_CLIENT_SECRET,
          undefined,
          {
            execute:
              process.env.NODE_ENV === "development" ||
              process.env.MODE === "docker"
                ? [client.allowInsecureRequests]
                : undefined,
          },
    );
```

```
ClientError: discovered metadata issuer does not match the expected issuer
2024-12-01 09:04:17     at file:///app/node_modules/openid-client/src/index.ts:1129:15
2024-12-01 09:04:17     at Module.discovery (file:///app/node_modules/openid-client/src/index.ts:1140:9)
2024-12-01 09:04:17     at processTicksAndRejections (node:internal/process/task_queues:105:5)
2024-12-01 09:04:17     at AuthService.getConfig (file:///app/apps/web/build/server/index.js?t=1733008018304.995:3495:20)
2024-12-01 09:04:17     at AuthService.getRedirectToLoginPage (file:///app/apps/web/build/server/index.js?t=1733008018304.995:3583:16)
2024-12-01 09:04:17     at AuthService.guardLoader (file:///app/apps/web/build/server/index.js?t=1733008018304.995:3687:39)
2024-12-01 09:04:17     at loader$2 (file:///app/apps/web/build/server/index.js?t=1733008018304.995:12881:23)
2024-12-01 09:04:17     at Object.callRouteLoader (/app/node_modules/@remix-run/server-runtime/dist/data.js:59:16)
2024-12-01 09:04:17     at /app/node_modules/@remix-run/router/router.ts:4899:19
2024-12-01 09:04:17     at callLoaderOrAction (/app/node_modules/@remix-run/router/router.ts:4963:16) {
2024-12-01 09:04:17   code: 'OAUTH_JSON_ATTRIBUTE_COMPARISON_FAILED',
2024-12-01 09:04:17   [cause]: {
2024-12-01 09:04:17     expected: 'http://identity-provider-web:8080/realms/hektor',
2024-12-01 09:04:17     body: {
2024-12-01 09:04:17       issuer: 'http://localhost:8080/realms/hektor',
2024-12-01 09:04:17       authorization_endpoint: 'http://localhost:8080/realms/hektor/protocol/openid-connect/auth',
2024-12-01 09:04:17       token_endpoint: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/token',
2024-12-01 09:04:17       introspection_endpoint: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/token/introspect',
2024-12-01 09:04:17       userinfo_endpoint: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/userinfo',
2024-12-01 09:04:17       end_session_endpoint: 'http://localhost:8080/realms/hektor/protocol/openid-connect/logout',
2024-12-01 09:04:17       frontchannel_logout_session_supported: true,
2024-12-01 09:04:17       frontchannel_logout_supported: true,
2024-12-01 09:04:17       jwks_uri: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/certs',
2024-12-01 09:04:17       check_session_iframe: 'http://localhost:8080/realms/hektor/protocol/openid-connect/login-status-iframe.html',
2024-12-01 09:04:17       grant_types_supported: [Array],
2024-12-01 09:04:17       acr_values_supported: [Array],
2024-12-01 09:04:17       response_types_supported: [Array],
2024-12-01 09:04:17       subject_types_supported: [Array],
2024-12-01 09:04:17       id_token_signing_alg_values_supported: [Array],
2024-12-01 09:04:17       id_token_encryption_alg_values_supported: [Array],
2024-12-01 09:04:17       id_token_encryption_enc_values_supported: [Array],
2024-12-01 09:04:17       userinfo_signing_alg_values_supported: [Array],
2024-12-01 09:04:17       userinfo_encryption_alg_values_supported: [Array],
2024-12-01 09:04:17       userinfo_encryption_enc_values_supported: [Array],
2024-12-01 09:04:17       request_object_signing_alg_values_supported: [Array],
2024-12-01 09:04:17       request_object_encryption_alg_values_supported: [Array],
2024-12-01 09:04:17       request_object_encryption_enc_values_supported: [Array],
2024-12-01 09:04:17       response_modes_supported: [Array],
2024-12-01 09:04:17       registration_endpoint: 'http://identity-provider-web:8080/realms/hektor/clients-registrations/openid-connect',
2024-12-01 09:04:17       token_endpoint_auth_methods_supported: [Array],
2024-12-01 09:04:17       token_endpoint_auth_signing_alg_values_supported: [Array],
2024-12-01 09:04:17       introspection_endpoint_auth_methods_supported: [Array],
2024-12-01 09:04:17       introspection_endpoint_auth_signing_alg_values_supported: [Array],
2024-12-01 09:04:17       authorization_signing_alg_values_supported: [Array],
2024-12-01 09:04:17       authorization_encryption_alg_values_supported: [Array],
2024-12-01 09:04:17       authorization_encryption_enc_values_supported: [Array],
2024-12-01 09:04:17       claims_supported: [Array],
2024-12-01 09:04:17       claim_types_supported: [Array],
2024-12-01 09:04:17       claims_parameter_supported: true,
2024-12-01 09:04:17       scopes_supported: [Array],
2024-12-01 09:04:17       request_parameter_supported: true,
2024-12-01 09:04:17       request_uri_parameter_supported: true,
2024-12-01 09:04:17       require_request_uri_registration: true,
2024-12-01 09:04:17       code_challenge_methods_supported: [Array],
2024-12-01 09:04:17       tls_client_certificate_bound_access_tokens: true,
2024-12-01 09:04:17       revocation_endpoint: 'http://localhost:8080/realms/hektor/protocol/openid-connect/revoke',
2024-12-01 09:04:17       revocation_endpoint_auth_methods_supported: [Array],
2024-12-01 09:04:17       revocation_endpoint_auth_signing_alg_values_supported: [Array],
2024-12-01 09:04:17       backchannel_logout_supported: true,
2024-12-01 09:04:17       backchannel_logout_session_supported: true,
2024-12-01 09:04:17       device_authorization_endpoint: 'http://localhost:8080/realms/hektor/protocol/openid-connect/auth/device',
2024-12-01 09:04:17       backchannel_token_delivery_modes_supported: [Array],
2024-12-01 09:04:17       backchannel_authentication_endpoint: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/ext/ciba/auth',
2024-12-01 09:04:17       backchannel_authentication_request_signing_alg_values_supported: [Array],
2024-12-01 09:04:17       require_pushed_authorization_requests: false,
2024-12-01 09:04:17       pushed_authorization_request_endpoint: 'http://identity-provider-web:8080/realms/hektor/protocol/openid-connect/ext/par/request',
2024-12-01 09:04:17       mtls_endpoint_aliases: [Object],
2024-12-01 09:04:17       authorization_response_iss_parameter_supported: true
2024-12-01 09:04:17     },
2024-12-01 09:04:17     attribute: 'issuer'
2024-12-01 09:04:17   }
2024-12-01 09:04:17 }
```

### Version

6.1.6

### Runtime

Node.js

### Runtime Details

Node 23.3.0

### Code to reproduce

```ts
const idpUrl = new URL(process.env.IDP_URL);

    const config = await client.discovery(
      idpUrl,
      process.env.IDP_CLIENT_ID,
      process.env.IDP_CLIENT_SECRET,
      undefined,
      {
        execute:
          process.env.NODE_ENV === "development" ||
          process.env.MODE === "docker"
            ? [client.allowInsecureRequests]
            : undefined,
      },
    );
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/openid-client/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
As per:

> https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation

> The issuer value returned MUST be identical to the Issuer URL that was used as the prefix to /.well-known/openid-configuration to retrieve the configuration information. This MUST also be identical to the iss Claim value in ID Tokens issued from this Issuer.

In your case

> 2024-12-01 09:04:17   code: 'OAUTH_JSON_ATTRIBUTE_COMPARISON_FAILED',
> 2024-12-01 09:04:17   [cause]: {
> 2024-12-01 09:04:17     expected: **'http://identity-provider-web:8080/realms/hektor'**,
> 2024-12-01 09:04:17     body: {
> 2024-12-01 09:04:17       issuer: **'http://localhost:8080/realms/hektor'**,
> 2024-12-01 09:04:17     },
> 2024-12-01 09:04:17     attribute: 'issuer'
> 2024-12-01 09:04:17   }

Please discuss this issue in the keycloak issue tracker.

**Comment by jezikk** [comment]
see https://github.com/keycloak/keycloak/issues/29783

**Comment by eplightning** [comment]
Wouldn't it be possible to add some config flag to make this check optional? It seems that this check is already skipped for some Microsoft stuff and I don't understand why do special exceptions for one specific provider instead of making it more general...

We use Keycloak with separate internal and external URL and this validation makes it impossible for us to ever upgrade from v5.

**Comment by jezikk** [comment]
We have the same problem in our project. In prod env we have the same url for front and back channel, but in DEV env the urls are different. So we cannot upgrade to v6. Some optional flag with warnings would be great.

**Comment by panva** [comment]
The MS cases are well documented public services. That cannot be said for local software installations.

If you want something specific for dev - instead of passing an issuer identifier pass the discovery document URL. Or fetch() your metadata yourself and use the Configuration constructor instead of discovery.

**Comment by jezikk** [comment]
Works for me too. Thanks all of you.

**Comment by panva** [comment]
Refs: https://github.com/panva/openid-client/commit/271ac5b0a4beeee5d3028bad2458cd5463f1bfc9
